##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##
# /home/ethanqjiang/workspace/curobo/curobo/src/curobo/content/configs/robot/xtrainer.yml
robot_cfg:
  kinematics:
    use_usd_kinematics: False
    urdf_path: "robot/ur_description/xtrainer.urdf"
    asset_root_path: "robot/ur_description"
    isaac_usd_path: "robot/ur_description/xtrainer/xtrainer.usd"
    usd_robot_root: "/xtrainer"
    usd_path: "robot/ur_description/xtrainer/xtrainer.usd"
    base_link: "LINK_0"
    ee_link: "gripper_link"
    link_names: null 
    collision_link_names: ['LINK_0','LINK_1','LINK_2', 'LINK_3', 'LINK_4', 'LINK_5' ,'LINK_6']
    collision_spheres: 'spheres/xtrainer.yml'
    collision_sphere_buffer: 0.00
    self_collision_ignore: {
      "LINK_0": ["LINK_1"],
      "LINK_1": ["LINK_2"],
      "LINK_2": ["LINK_1","LINK_3"],
      "LINK_3": ["LINK_2", "LINK_4"],
      "LINK_4": ["LINK_3", "LINK_5"],
      "LINK_5": ["LINK_4", "LINK_6"],
      "LINK_6": ["LINK_5"]      
    }
    self_collision_buffer: {
      "LINK_0": 0,
      'LINK_1': 0, 
      'LINK_2': 0, 
      'LINK_3': 0, 
      'LINK_4': 0,
      'LINK_5' : 0, 
      'LINK_6': 0,
    }
    mesh_link_names: [ 'LINK_0','LINK_1','LINK_2', 'LINK_3', 'LINK_4', 'LINK_5' ,'LINK_6' ]
    lock_joints: null

    cspace:
      joint_names: [ 'J_1','J_2', 'J_3', 'J_4', 'J_5' ,'J_6' ]
      retract_config: [1,1,1,1,1,1]
      null_space_weight: [1.0, 1.0, 1.0, 1.0, 1.0,1.0]
      cspace_distance_weight: [2.5, 1.75, 1.5, 1.25, 0.7, 0.4] #[2.5, 1.75, 1.5, 1.25, 0.7, 0.4]
      max_jerk: 500.0
      max_acceleration: 12.0
      position_limit_clip: 0.1
      # add velocity scaling
      # add joint position limit clipping
